#!/bin/sh

CONFIG_PATH="/etc/TasmotaSimulator.json"
DEFAULT_CONFIG="/usr/share/TasmotaSimulator/etc/TasmotaSimulator.json"

# Only copy default config if it doesn't already exist
if [ ! -f "$CONFIG_PATH" ]; then
	echo "using default config"
    cp "$DEFAULT_CONFIG" "$CONFIG_PATH"
else
	echo "keeping old config"
fi


# Only run after installation
[ "$1" = "configure" ] || exit 0

# Enable and start the service
/etc/init.d/TasmotaSimulator enable
/etc/init.d/TasmotaSimulator start

exit 0