#!/bin/sh

# Stop and disable the service before files are removed
/etc/init.d/TasmotaSimulator stop
/etc/init.d/TasmotaSimulator disable


CONFIG_PATH="/etc/TasmotaSimulator.json"
DEFAULT_CONFIG="/usr/share/TasmotaSimulator/etc/TasmotaSimulator.json"

# Compare files using checksum
if cmp -s "$CONFIG_PATH" "$DEFAULT_CONFIG"; then
    echo "Removing default config file"
    rm "$CONFIG_PATH"
else
    echo "config file is modified,"
	echo "preserving ${CONFIG_PATH}"
fi

