#!/bin/sh

CONFIG_PATH="/etc/Serial2MqttArduinoDs18b20.json"
DEFAULT_CONFIG="/usr/share/Serial2MqttArduinoDs18b20/etc/Serial2MqttArduinoDs18b20.json"

# Only copy default config if it doesn't already exist
if [ ! -f "$CONFIG_PATH" ]; then
	echo "using default config"
    cp "$DEFAULT_CONFIG" "$CONFIG_PATH"
else
	echo "keeping old config"
fi


# Only run after installation
[ "$1" = "configure" ] || exit 0

# Enable and start the service
/etc/init.d/Serial2MqttArduinoDs18b20 enable
/etc/init.d/Serial2MqttArduinoDs18b20 start

exit 0