#!/bin/sh

CONFIG_PATH="/etc/BrfHeatControl.json"
DEFAULT_CONFIG="/usr/share/BrfHeatControl/etc/BrfHeatControl.json"

# Only copy default config if it doesn't already exist
if [ ! -f "$CONFIG_PATH" ]; then
	echo "using default config"
    cp "$DEFAULT_CONFIG" "$CONFIG_PATH"
else
	echo "keeping old config"
fi


# Only run after installation
[ "$1" = "configure" ] || exit 0

# Enable and start the service
/etc/init.d/BrfHeatControl enable
/etc/init.d/BrfHeatControl start

exit 0