#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1
SOCAT_PIDFILE=/var/run/socat_output.Serial2MqttArduinoDs18b20.pid

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/Serial2MqttArduinoDs18b20
    procd_set_param respawn 3600 5 10  # Restart if it crashes: 1hr timeout, 5 retries, no delay
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_set_param pidfile /var/run/Serial2MqttArduinoDs18b20.pid
	procd_set_param file /etc/Serial2MqttArduinoDs18b20.json
    procd_close_instance
}

stop_service() {
	echo "Stopping socat..."
    if [ -f "$SOCAT_PIDFILE" ]; then
        kill "$(cat $SOCAT_PIDFILE)" 2>/dev/null
        rm -f "$SOCAT_PIDFILE"
   # else
   #     echo "PID file not found. Is socat running?"
    fi
}
