#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

CONFIG_FILE="/etc/TasmotaSimulator.json"

should_start(){
    local simulated
    simulated=$(grep '"Simulated"' "$CONFIG_FILE" | awk -F: '{gsub(/[ ,"]/,"",$2); print $2}')
    [ "$simulated" -eq 1 ] 	
}

start_service() {
	if should_start; then
		procd_open_instance
		procd_set_param command /usr/bin/TasmotaSimulator
		procd_set_param respawn 3600 5 10  # Restart if it crashes: 1hr timeout, 5 retries, no delay
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param pidfile /var/run/TasmotaSimulator.pid
		procd_set_param file /etc/TasmotaSimulator.json
		procd_close_instance
		echo "Skipping service: Simulated mode is ON"
	else
		echo "Skipping service: Simulated mode is OFF"
    fi

}

stop_service() {
	echo stopping
}
