#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1
SOCAT_PIDFILE=/var/run/socat_output.SerialMqttArduinoDs18b20_Relays.pid

stopsocat()
{
	echo "Stopping socat..."
    if [ -f "$SOCAT_PIDFILE" ]; then
        kill "$(cat $SOCAT_PIDFILE)" 2>/dev/null
        rm -f "$SOCAT_PIDFILE"
   # else
   #     echo "PID file not found. Is socat running?"
    fi
}


start_service() {
	#stop old socat before a restart
    procd_open_instance
    procd_set_param command /usr/bin/SerialMqttArduinoDs18b20_Relays
    procd_set_param respawn 3600 5 10  # Restart if it crashes: 1hr timeout, 5 retries, no delay
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_set_param pidfile /var/run/SerialMqttArduinoDs18b20_Relays.pid
	procd_set_param file /etc/SerialMqttArduinoDs18b20_Relays.json
    procd_close_instance
}

stop_service() {
	stopsocat

}
