#!/bin/sh

CONFIG_PATH="/etc/SerialMqttArduinoDs18b20_Relays.json"
DEFAULT_CONFIG="/usr/share/SerialMqttArduinoDs18b20_Relays/etc/SerialMqttArduinoDs18b20_Relays.json"

# Only copy default config if it doesn't already exist
if [ ! -f "$CONFIG_PATH" ]; then
	echo "using default config"
    cp "$DEFAULT_CONFIG" "$CONFIG_PATH"
else
	echo "keeping old config"
fi


# Only run after installation
[ "$1" = "configure" ] || exit 0

# Enable and start the service
/etc/init.d/SerialMqttArduinoDs18b20_Relays enable
/etc/init.d/SerialMqttArduinoDs18b20_Relays start

exit 0