#!/bin/sh

# Stop and disable the service before files are removed
/etc/init.d/SerialMqttArduinoDs18b20_Relays stop
/etc/init.d/SerialMqttArduinoDs18b20_Relays disable


CONFIG_PATH="/etc/SerialMqttArduinoDs18b20_Relays.json"
DEFAULT_CONFIG="/usr/share/SerialMqttArduinoDs18b20_Relays/etc/SerialMqttArduinoDs18b20_Relays.json"

# Compare files using checksum
if cmp -s "$CONFIG_PATH" "$DEFAULT_CONFIG"; then
    echo "Removing default config file"
    rm "$CONFIG_PATH"
else
    echo "config file is modified,"
	echo "preserving ${CONFIG_PATH}"
fi

